name: Modify GitHub Actions workflow for practice
on:  workflow_dispatch
jobs:
  practice:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: |
        echo "Line1"
        echo "Line2"
        echo "Line3"
